"""Build a TITLE-FREE suite: questions answered by one passage that never name it.

Why. Every answerable question in the title suites names its own article -
golden 40/40, serving_golden 60/60, holdout 13/15 ("What is Biotite?"). Recall
on those measures title lookup. A keyword retriever would score perfectly by
construction and a reranker has nothing to improve, so neither hybrid search
nor reranking can be judged on them. These suites ask about a FACT in a passage
without naming the article it comes from.

The questions are written by hand, not generated by the model under test. So
building one is three steps:

  sample  Seeded, deterministic choice of passages: one chunk per article,
          articles and chunks drawn by a fixed seed, lists and disambiguation
          pages excluded. Writes eval/detail_work/<suite>.candidates.jsonl.
  draft   One line per candidate in eval/detail_work/<suite>.drafts.jsonl:
          {"cid", "question", "answer"} with `answer` copied VERBATIM from the
          passage, or {"cid", "skip": "<reason>"} for a passage with no
          question worth asking. Every drafted case is reviewed by a person
          before the suite is committed.
  build   Joins the two, VERIFIES CORPUS PROPERTIES, writes eval/<suite>.jsonl.

THE VERIFICATION RULE - the one build_serving_suite.py follows:

    Verify CORPUS properties. Never verify SYSTEM BEHAVIOUR.

  every case     the question uses no word of its article's title, and does not
                 contain its own answer
  answerable     the article is indexed; the answer occurs in the passage
  unanswerable   the article is NOT indexed, and the answer occurs NOWHERE in
                 the indexed corpus - checked by scanning every chunk

Nothing here checks whether retrieval finds anything. That is what the eval is
for, and a builder that kept only the cases the system already gets right would
score 1.0 by construction.

Stated limits: absence is checked as a string, so an answer present only as a
paraphrase would pass as absent; and an answerable fact may also occur in
another article, which the suite will score as a miss if that article ranks
first. Distinctive facts were preferred when drafting for that reason.

Usage:
    uv run python scripts/build_detail_suite.py sample --suite detail
    uv run python scripts/build_detail_suite.py build --suite detail
"""

from __future__ import annotations

import argparse
import gzip
import json
import random
import re
import sys
from pathlib import Path

BACKEND = Path(__file__).resolve().parents[1] / "backend"
sys.path.insert(0, str(BACKEND))

from eval.suites import names_its_title, normalize, suite_path  # noqa: E402

WORK_DIR = BACKEND / "eval" / "detail_work"
FIXTURE = BACKEND / "eval" / "fixtures" / "corpus_eval.jsonl.gz"
SEED = 20260921
MIN_PASSAGE_CHARS = 800
MIN_PASSAGE_SENTENCES = 5
SPARE = 1.5  # sample extra so skipped passages still leave enough cases

PRESETS = {
    # Fixture corpus: reproducible in CI. Unanswerable passages come from the
    # served corpus, from articles the 150-article fixture does not contain.
    "detail": {
        "collection": "wikipedia_eval",
        "prefix": "dt",
        "answerable": 40,
        "unanswerable": 20,
        "unanswerable_from": "wikipedia",
    },
    # Served corpus. Unanswerable passages come from the held-out slice, which
    # is excluded from ingestion by construction (app.core.holdout).
    "serving_detail": {
        "collection": "wikipedia",
        "prefix": "sd",
        "answerable": 60,
        "unanswerable": 20,
        "unanswerable_from": "held_out",
    },
}

_LIST_TITLE = re.compile(r"^(lists? of|index of|outline of|timeline of)\b|\(disambiguation\)$",
                         re.IGNORECASE)


def eligible_title(title: str) -> bool:
    return len(title) > 2 and not _LIST_TITLE.search(title) and not title.strip().isdigit()


def good_passage(text: str) -> bool:
    """Prose, not a table or a list: long enough, with real sentences."""
    return len(text) >= MIN_PASSAGE_CHARS and len(re.findall(r"[a-z]\. ", text)) >= (
        MIN_PASSAGE_SENTENCES - 1
    )


def fixture_titles_and_texts() -> dict[str, str]:
    with gzip.open(FIXTURE, "rt", encoding="utf-8") as handle:
        return {row["title"]: row["text"] for row in map(json.loads, handle)}


def ids_by_title(client, collection: str) -> dict[str, list]:
    grouped: dict[str, list] = {}
    offset = None
    while True:
        points, offset = client.scroll(collection_name=collection, limit=4096, offset=offset,
                                       with_payload=["title"], with_vectors=False)
        for point in points:
            title = (point.payload or {}).get("title")
            if title:
                grouped.setdefault(title, []).append(point.id)
        if offset is None:
            return grouped


def corpus_texts(client, collection: str):
    offset = None
    while True:
        points, offset = client.scroll(collection_name=collection, limit=2048, offset=offset,
                                       with_payload=["text"], with_vectors=False)
        for point in points:
            yield (point.payload or {}).get("text", "")
        if offset is None:
            return


def sample_indexed(client, collection: str, wanted: int, rng: random.Random,
                   exclude: set[str] = frozenset()) -> list[dict]:
    grouped = ids_by_title(client, collection)
    titles = sorted(t for t in grouped if eligible_title(t) and t not in exclude)
    rng.shuffle(titles)
    chosen: list[dict] = []
    for title in titles:
        if len(chosen) >= wanted:
            break
        ids = sorted(grouped[title], key=str)
        rng.shuffle(ids)
        for point in client.retrieve(collection_name=collection, ids=ids[:3], with_payload=True):
            text = (point.payload or {}).get("text", "")
            if good_passage(text):
                chosen.append({"title": title, "source_id": point.payload.get("source_id", ""),
                               "text": text})
                break
    return chosen


def sample_held_out(wanted: int, rng: random.Random, indexed: set[str],
                    scan_limit: int = 12_000) -> list[dict]:
    from app.core.chunking import chunk_text
    from app.core.holdout import is_held_out
    from pipeline.sources import iter_articles

    chosen: list[dict] = []
    for index, article in enumerate(iter_articles("real")):
        if index >= scan_limit or len(chosen) >= wanted:
            break
        title = article["title"]
        if not is_held_out(article["id"]) or title in indexed or not eligible_title(title):
            continue
        chunks = [c for c in chunk_text(article["text"], article["id"]) if good_passage(c.text)]
        if chunks:
            chunk = rng.choice(chunks)
            chosen.append({"title": title, "source_id": article["id"], "text": chunk.text})
    return chosen


def cmd_sample(suite: str, url: str) -> int:
    from qdrant_client import QdrantClient

    preset = PRESETS[suite]
    rng = random.Random(SEED)
    client = QdrantClient(url=url, timeout=300)
    wanted = int(preset["answerable"] * SPARE)
    answerable = sample_indexed(client, preset["collection"], wanted, rng)

    if preset["unanswerable_from"] == "held_out":
        indexed = set(ids_by_title(client, preset["collection"]))
        unanswerable = sample_held_out(int(preset["unanswerable"] * SPARE), rng, indexed)
    else:
        unanswerable = sample_indexed(
            client, preset["unanswerable_from"], int(preset["unanswerable"] * SPARE), rng,
            exclude=set(fixture_titles_and_texts()),
        )

    rows = [
        {"cid": f"{preset['prefix']}-a-{i:03d}", "kind": "answerable", **c}
        for i, c in enumerate(answerable)
    ] + [
        {"cid": f"{preset['prefix']}-u-{i:03d}", "kind": "unanswerable", **c}
        for i, c in enumerate(unanswerable)
    ]
    WORK_DIR.mkdir(parents=True, exist_ok=True)
    out = WORK_DIR / f"{suite}.candidates.jsonl"
    out.write_text("\n".join(json.dumps(r, ensure_ascii=False) for r in rows) + "\n",
                   encoding="utf-8")
    print(f"wrote {out}: {len(answerable)} answerable, {len(unanswerable)} unanswerable candidates")
    return 0


_EVIDENCE_WORD = re.compile(r"[^\W_]+")


def _clip(sentence: str, wanted: str, width: int = 400) -> str:
    """The sentence, or a window of it centred on the answer when it is long."""
    if len(sentence) <= width:
        return sentence
    at = max(0, sentence.casefold().find(wanted))
    start = max(0, at - width // 2)
    return sentence[start:start + width]


def evidence_sentence(text: str, answer: str, question: str = "") -> str:
    """The passage sentence that answers the question, for a reviewer to check.

    Of the sentences holding the answer, the one sharing most words with the
    question. When a different sentence matches the question much better - a
    quote attributed with "He" rather than the name - both are shown.

    Falls back to a window around the answer when no single "sentence" holds
    it: an answer like "St. Jacob's Church" or "Dr. Suwelack" contains a period
    the sentence split treats as a boundary.
    """
    wanted = normalize(answer)
    asked = {w for w in _EVIDENCE_WORD.findall(question.lower()) if len(w) > 3}
    sentences = [s.strip() for s in re.split(r"(?<=[.!?])\s+|\n+", text) if s.strip()]

    def overlap(sentence: str) -> int:
        return len(asked & set(_EVIDENCE_WORD.findall(sentence.lower())))

    holding = [s for s in sentences if wanted in normalize(s)]
    if holding:
        best = max(holding, key=overlap)
        closest = max(sentences, key=overlap)
        if closest is not best and overlap(closest) >= overlap(best) + 2:
            return f"{closest[:250]} [...] {_clip(best, wanted, 250)}"
        return _clip(best, wanted)
    flat = " ".join(text.split())
    at = flat.casefold().find(wanted)
    if at < 0:
        return ""
    start, end = max(0, at - 150), min(len(flat), at + len(wanted) + 150)
    return flat[start:end].strip()


def case_problems(candidate: dict, draft: dict) -> list[str]:
    """Checks that need no corpus scan. Returned as reasons, never raised."""
    problems = []
    question, answer = draft["question"].strip(), draft["answer"].strip()
    if not question.endswith("?"):
        problems.append("question does not end with '?'")
    if named := names_its_title(question, candidate["title"]):
        problems.append(f"question names its article: {sorted(named)}")
    if normalize(answer) in normalize(question):
        problems.append("question contains its own answer")
    if normalize(answer) not in normalize(candidate["text"]):
        problems.append("answer is not verbatim in the passage")
    return problems


def cmd_build(suite: str, url: str) -> int:
    from qdrant_client import QdrantClient

    preset = PRESETS[suite]
    candidates = [json.loads(line) for line in
                  (WORK_DIR / f"{suite}.candidates.jsonl").read_text(encoding="utf-8").splitlines()
                  if line.strip()]
    drafts = {d["cid"]: d for d in (json.loads(line) for line in
              (WORK_DIR / f"{suite}.drafts.jsonl").read_text(encoding="utf-8").splitlines()
              if line.strip())}

    client = QdrantClient(url=url, timeout=300)
    indexed = set(ids_by_title(client, preset["collection"]))

    failures: list[str] = []
    accepted = {"answerable": [], "unanswerable": []}
    for candidate in candidates:
        draft = drafts.get(candidate["cid"])
        if draft is None or draft.get("skip"):
            continue
        problems = case_problems(candidate, draft)
        in_index = candidate["title"] in indexed
        if candidate["kind"] == "answerable" and not in_index:
            problems.append("answerable article is not indexed")
        if candidate["kind"] == "unanswerable" and in_index:
            problems.append("unanswerable article IS indexed")
        if problems:
            failures.append(f"{candidate['cid']}: {'; '.join(problems)}")
        accepted[candidate["kind"]].append((candidate, draft))

    # One scan of the indexed corpus: no unanswerable answer may occur anywhere in it.
    absent = {normalize(d["answer"]): c["cid"] for c, d in accepted["unanswerable"]}
    for text in corpus_texts(client, preset["collection"]):
        haystack = normalize(text)
        for answer in [a for a in absent if a in haystack]:
            failures.append(f"{absent.pop(answer)}: unanswerable answer {answer!r} is indexed")
    if suite == "detail":
        # The fixture file is a superset of what is indexed: hold it to that too.
        for title, text in fixture_titles_and_texts().items():
            haystack = normalize(text)
            for answer in [a for a in absent if a in haystack]:
                failures.append(f"{absent.pop(answer)}: answer {answer!r} is in fixture '{title}'")

    for kind in ("answerable", "unanswerable"):
        if len(accepted[kind]) < preset[kind]:
            failures.append(f"only {len(accepted[kind])} {kind} drafted, need {preset[kind]}")
    if failures:
        print("NOT WRITTEN - fix the drafts:\n  " + "\n  ".join(failures))
        return 1

    rows = []
    for kind, expected_refusal in (("answerable", False), ("unanswerable", True)):
        for candidate, draft in accepted[kind][: preset[kind]]:
            rows.append({
                # The passage's id, not a running number: skipping one passage
                # must not renumber every case after it, or a resumed end-to-end
                # run would file answers under the wrong question.
                "id": candidate["cid"],
                "category": "detail" if kind == "answerable" else "out_of_corpus_detail",
                "question": draft["question"].strip(),
                "expected_titles": [] if expected_refusal else [candidate["title"]],
                "expected_refusal": expected_refusal,
                "answer": draft["answer"].strip(),
                "source_article": candidate["title"],
                "source_id": candidate["source_id"],
                "evidence": evidence_sentence(
                    candidate["text"], draft["answer"], draft["question"]
                ),
            })
    out = suite_path(suite)
    out.write_text("\n".join(json.dumps(r, ensure_ascii=False) for r in rows) + "\n",
                   encoding="utf-8")
    print(f"wrote {out}: {preset['answerable']} answerable, {preset['unanswerable']} unanswerable")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("step", choices=("sample", "build"))
    parser.add_argument("--suite", choices=sorted(PRESETS), required=True)
    parser.add_argument("--url", default="http://127.0.0.1:6333")
    args = parser.parse_args()
    return (cmd_sample if args.step == "sample" else cmd_build)(args.suite, args.url)


if __name__ == "__main__":
    sys.exit(main())
